# All identifiers for dash components used in specxplore

CYTOSCAPE_MAIN_PANEL = "cytoscape-main-panel"
FIGURE_EDGE_WEIGHT_HISTOGRAM = "figure-edge-weight-histogram"
PANEL_HOVER_INFO = "hover-info-panel"
PANEL_OFFCANVAS_SETTINGS = "offcanvas-settings-panel"
PANEL_OFFCANVAS_FOCUS_SPECTRUM_ILOC_SELECTION = "panel-offcanvas-focus-spectrum-iloc-selection"
PANEL_NODE_DEGREE_LEGEND = "panel-node-degree-legend"
PANEL_WARNING_MESSAGES_1 = "panel-warning-messages-1"
PANEL_WARNING_MESSAGES_2 = "panel-warning-messages-2"
PANEL_DETAIL_VISUALIZATIONS = "panel-detail-visualizations"
PANEL_GRAPH_SPECPLOT = "panel-graph-specplot"
PANEL_METADATA_TABLE = "panel-metadata-table"

STORE_EDGE_THRESHOLD = "store-edge-threshold"
STORE_HOP_DISTANCE = "store-hop-distance"
STORE_EMPTY_SESSION_DATA_TRIGGER = "store-empty-session-data-trigger"
STORE_MAXIMUM_NODE_DEGREE = "store-maximum-node-degree"
STORE_SELECTED_CLASS_LEVEL = "store-selected-class-level"
STORE_CLASSES_TO_BE_HIGHLIGHTED = "store-classes-to-be-highlighted"
STORE_NODE_ELEMENTS = "store-node-elements"
STORE_COLORBLIND_BOOLEAN = "store-colorblind-boolean"

INPUT_EDGE_THRESHOLD = "input-edge-threshold"
INPUT_COORDINATE_SCALING = "input-scaler-id"
INPUT_TOP_K_FRAGMENT_LIMIT_FOR_FRAGMAP = "top-k-fragment-limit-for-fragmap"
INPUT_MAXIMUM_NODE_DEGREE = "input-maximum-node-degree"
INPUT_HOP_DISTANCE = "input-hop-distance"
INPUT_UPLOAD_NEW_SESSION_DATA = "input-upload-new-session-data"

SWITCH_AUGMAP_COLORBLIND_CHANGE = "switch-augmap-colorblind-change"

DROPDOWN_SELECT_CLASS_LEVEL = "dropdown-select-class-level"
DROPDOWN_CLASSES_TO_BE_HIGHLIGHTED = "dropdown-classes-to-be-highlighted"
DROPDOWN_FOCUS_SPECTRUM_ILOC_SELECTION = "dropdown-focus-spectrum-iloc-selection"

BUTTON_OPEN_SETTINGS = "button-open-settings"
BUTTON_OPEN_FOCUS = "button-open-focus"
BUTTON_RUN_DEGREE_MAP = "button-run-degree-map"
BUTTON_RUN_EGONET = "button-run-egonet"
BUTTON_RUN_NETVIEW = "button-run-netview"
BUTTON_RUN_AUGMAP = "button-run-augmap"
BUTTON_RUN_SPECPLOT = "button-run-specplot"
BUTTON_RUN_FRAGMAP = "button-run-fragmap"
BUTTON_RUN_METADATA_TABLE = "button-run-metadata-table"