name: automatic testing & dependency evaluation

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        fail-fast: [false]
        python-version: ["3.8"]
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest'] # , 'macos-latest'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install cython
          python setup.py build_ext --inplace
          python setup.py install
      - name: Test with pytest
        run: |
          pytest